interface Env {
  SITES: {
    get(
      key: string,
    ): Promise<{
      body: ReadableStream<Uint8Array>;
      httpEtag?: string;
      httpMetadata?: {
        contentType?: string;
        cacheControl?: string;
        contentLanguage?: string;
        contentDisposition?: string;
        contentEncoding?: string;
      };
    } | null>;
  };
}

const ROOT_DOMAIN = "fellacoo.xyz";

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
};

function responseHeaders(
  contentType: string,
  etag?: string,
  cacheControl = "public, max-age=60, s-maxage=300",
) {
  const headers = new Headers({
    "Content-Type": contentType,
    "Cache-Control": cacheControl,
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "X-Frame-Options": "SAMEORIGIN",
  });

  if (etag) headers.set("ETag", etag);

  return headers;
}

function getSiteSlug(hostname: string) {
  const suffix = "." + ROOT_DOMAIN;

  if (!hostname.endsWith(suffix)) return null;

  const slug = hostname.slice(0, -suffix.length).toLowerCase();

  if (!slug || slug.includes(".") || slug === "www") return null;
  if (!/^[a-z0-9](?:[a-z0-9-]{0,46}[a-z0-9])?$/.test(slug)) return null;

  return slug;
}

function safePath(pathname: string) {
  const decoded = decodeURIComponent(pathname);

  if (decoded.includes("\\") || decoded.split("/").some((segment) => segment === "..")) {
    return null;
  }

  return decoded;
}

function keyFor(slug: string, pathname: string) {
  const path = pathname.replace(/^\/+/, "").replace(/\/+$/, "");

  if (!path) return `sites/${slug}/index.html`;

  // Generated website pages are published as:
  // sites/<slug>/<page-path>/index.html
  // Static files, if added later, are served directly from sites/<slug>/...
  if (path.endsWith(".html") || path.includes(".")) {
    return `sites/${slug}/${path}`;
  }

  return `sites/${slug}/${path}/index.html`;
}

async function getObject(env: Env, key: string) {
  return env.SITES.get(key);
}

async function serveObject(
  request: Request,
  env: Env,
  key: string,
) {
  const object = await getObject(env, key);

  if (!object) {
    return new Response("Site page not found", {
      status: 404,
      headers: responseHeaders("text/plain; charset=utf-8", undefined, "no-store"),
    });
  }

  const url = new URL(request.url);
  const pathname = url.pathname;
  const extension = pathname.match(/\.[a-z0-9]+$/i)?.[0]?.toLowerCase() ?? ".html";
  const contentType =
    object.httpMetadata?.contentType ??
    CONTENT_TYPES[extension] ??
    "application/octet-stream";

  const headers = responseHeaders(
    contentType,
    object.httpEtag,
    extension === ".html"
      ? "public, max-age=60, s-maxage=300, stale-while-revalidate=86400"
      : "public, max-age=31536000, immutable",
  );

  if (request.method === "HEAD") {
    return new Response(null, { status: 200, headers });
  }

  return new Response(object.body, { status: 200, headers });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method not allowed", {
        status: 405,
        headers: {
          Allow: "GET, HEAD",
          "Cache-Control": "no-store",
        },
      });
    }

    const url = new URL(request.url);
    const slug = getSiteSlug(url.hostname);

    if (!slug) {
      return new Response("Unknown Fellacoo site", {
        status: 404,
        headers: {
          "Content-Type": "text/plain; charset=utf-8",
          "Cache-Control": "no-store",
        },
      });
    }

    const pathname = safePath(url.pathname);
    if (pathname === null) {
      return new Response("Invalid path", {
        status: 400,
        headers: { "Cache-Control": "no-store" },
      });
    }

    // /about -> /about/ keeps the public URLs canonical and matches
    // the directory-style objects generated by the publisher.
    if (
      pathname !== "/" &&
      !pathname.endsWith("/") &&
      !pathname.split("/").pop()?.includes(".")
    ) {
      const redirectUrl = new URL(request.url);
      redirectUrl.pathname += "/";
      return Response.redirect(redirectUrl.toString(), 308);
    }

    const key = keyFor(slug, pathname);
    return serveObject(request, env, key);
  },
};
